#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mia[-1]
	add ucitrack mia
	set ucitrack.@mia[-1].init=mia
	commit ucitrack

	delete firewall.mia
	set firewall.mia=include
	set firewall.mia.type=script
	set firewall.mia.path=/etc/mia.include
	set firewall.mia.reload=1
	commit firewall
EOF

# 给 mia 文件添加可执行权限
chmod a+x /etc/init.d/mia

rm -f /tmp/luci-indexcache
exit 0
