#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@qbittorrent[-1]
	add ucitrack qbittorrent
	set ucitrack.@qbittorrent[-1].init=qbittorrent
	commit ucitrack
EOF

mkdir /opt

# 给 qbittorrent 文件添加可执行权限
chmod a+x /etc/init.d/qbittorrent

rm -f /tmp/luci-indexcache*
exit 0
